In [1]:
import glob
import h5py
# import matplotlib.pyplot as plt
from multiscale_new import *
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error
import sys

In [2]:
train_files = glob.glob('PMMA*train.csv')
print(train_files)
test_files = glob.glob('PMMA*test.csv')
print(test_files)

['PMMAboundary_GASP_location_train.csv', 'PMMAboundary_GASP_sample_train.csv']
['PMMAboundary_GASP_location_test.csv', 'PMMAboundary_GASP_sample_test.csv']


In [3]:
qoi = 'rdot' # 'rdot' or 'qtot'
j = 0 # 0, 1, 2, or 3
k = 1 # 1, or 2
# ss = 12

In [4]:
Data = pd.read_csv(train_files[1])
# Data = Data.dropna()
Data = np.array(Data.values)

if qoi == 'rdot':
    Data = np.hstack((Data[:, 3:-1], Data[:, 1].reshape(-1, 1))).astype(float)
else:
    Data = np.hstack((Data[:, 3:-1], Data[:, 2].reshape(-1, 1))).astype(float)
    
max_cols = np.diag([1/max(Data[:, i]) for i in range(len(Data[0]))])
Data = np.matmul(Data, max_cols)
print(Data)
print(len(Data))

Cs = glob.glob('Cs*.npy')
print(Cs)
sparse = glob.glob('sparse*.npy')
print(sparse)
T = glob.glob('T*.npy')
print(T)

[[0.70590027 1.         0.98737823 ... 0.76488178 0.68129824 0.06561907]
 [0.75709935 1.         0.98737823 ... 0.76488178 0.68129824 0.06550133]
 [0.76771265 1.         0.98737823 ... 0.76488178 0.68129824 0.06420685]
 ...
 [0.22179105 0.10612479 0.98494404 ... 0.68782473 0.44799568 0.        ]
 [0.22936649 0.17687465 0.98494404 ... 0.68782473 0.44799568 0.01645269]
 [0.23694193 0.24762451 0.98494404 ... 0.68782473 0.44799568 0.04733215]]
4784
['Cs__0.002_rdot_sample.npy', 'Cs__0.005_qtot_location.npy', 'Cs__0.005_qtot_sample.npy', 'Cs__0.005_rdot_location.npy', 'Cs__0.005_rdot_sample.npy']
['sparse__0.002_rdot_sample.npy', 'sparse__0.005_qtot_location.npy', 'sparse__0.005_qtot_sample.npy', 'sparse__0.005_rdot_location.npy', 'sparse__0.005_rdot_sample.npy']
['T__0.002_rdot_sample.npy', 'T__0.005_qtot_location.npy', 'T__0.005_qtot_sample.npy', 'T__0.005_rdot_location.npy', 'T__0.005_rdot_sample.npy']


In [5]:
Cs = np.load(Cs[j])
sparse = np.load(sparse[j])
T = np.load(T[j])

# predict(Data[:, :-1],sparse,T,Cs)
truth = np.array(pd.read_csv(train_files[1]).values)
# truth = truth[:, 2]/np.max(truth[:, 2])
mean_squared_error(truth[:, k]/np.max(truth[:, k]), predict(Data[:, :-1],sparse,T,Cs))

3.5056634245109066e-06

In [6]:
test = np.array(pd.read_csv(test_files[1]).values)
# test = test[:, 2]/np.max(truth[:, 2])
mean_squared_error(test[:, k]/np.max(truth[:, k]), predict(np.matmul(test[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs))

0.0006650508483947287

In [7]:
Data = np.array(pd.read_csv(train_files[1]).values)
Data = np.array([Data[92*i+80] for i in range(52)])
# mean_squared_error(Data[:, k]/np.max(truth[:, k]), predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs))
errors = Data[:, k]/np.max(truth[:, k]) - predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs)
squared_errors = [error**2 for error in errors]
np.mean(squared_errors)

1.8011614281773743e-06

In [8]:
Data = np.array(pd.read_csv(test_files[1]).values)
Data = np.array([Data[92*i+80] for i in range(12)])
# mean_squared_error(Data[:, k]/np.max(truth[:, k]), predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs))
errors = Data[:, k]/np.max(truth[:, k]) - predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs)
squared_errors = [error**2 for error in errors]
np.mean(squared_errors)

3.062037566655271e-05

In [9]:
Data = np.array(pd.read_csv(train_files[1]).values)
Data = np.array([Data[92*i+90] for i in range(52)])
# mean_squared_error(Data[:, k]/np.max(truth[:, k]), predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs))
errors = Data[:, k]/np.max(truth[:, k]) - predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs)
squared_errors = [error**2 for error in errors]
np.mean(squared_errors)

1.5557902485148497e-06

In [10]:
Data = np.array(pd.read_csv(test_files[1]).values)
Data = np.array([Data[92*i+90] for i in range(12)])
# mean_squared_error(Data[:, k]/np.max(truth[:, k]), predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs))
errors = Data[:, k]/np.max(truth[:, k]) - predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs)
squared_errors = [error**2 for error in errors]
np.mean(squared_errors)

4.842483128319038e-05

In [11]:
Data = np.array(pd.read_csv(train_files[1]).values)
Data = np.array([Data[92*i+49] for i in range(52)])
# mean_squared_error(Data[:, k]/np.max(truth[:, k]), predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs))
errors = Data[:, k]/np.max(truth[:, k]) - predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs)
squared_errors = [error**2 for error in errors]
np.mean(squared_errors)

4.507789592741175e-06

In [12]:
Data = np.array(pd.read_csv(test_files[1]).values)
Data = np.array([Data[92*i+49] for i in range(12)])
# mean_squared_error(Data[:, k]/np.max(truth[:, k]), predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs))
errors = Data[:, k]/np.max(truth[:, k]) - predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs)
squared_errors = [error**2 for error in errors]
np.mean(squared_errors)

4.250862255748252e-05

In [13]:
Data = np.array(pd.read_csv(train_files[1]).values)
Data = np.array([Data[92*i+38] for i in range(52)])
# mean_squared_error(Data[:, k]/np.max(truth[:, k]), predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs))
errors = Data[:, k]/np.max(truth[:, k]) - predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs)
squared_errors = [error**2 for error in errors]
np.mean(squared_errors)

2.081312218069052e-05

In [14]:
Data = np.array(pd.read_csv(test_files[1]).values)
Data = np.array([Data[92*i+38] for i in range(12)])
# mean_squared_error(Data[:, k]/np.max(truth[:, k]), predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs))
errors = Data[:, k]/np.max(truth[:, k]) - predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs)
squared_errors = [error**2 for error in errors]
np.mean(squared_errors)

0.0005617974326138693

In [15]:
Data = np.array(pd.read_csv(train_files[1]).values)
Data = np.array([Data[92*i+43] for i in range(52)])
# mean_squared_error(Data[:, k]/np.max(truth[:, k]), predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs))
errors = Data[:, k]/np.max(truth[:, k]) - predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs)
squared_errors = [error**2 for error in errors]
np.mean(squared_errors)

6.996297753760536e-07

In [16]:
Data = np.array(pd.read_csv(test_files[1]).values)
Data = np.array([Data[92*i+43] for i in range(12)])
# mean_squared_error(Data[:, k]/np.max(truth[:, k]), predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs))
errors = Data[:, k]/np.max(truth[:, k]) - predict(np.matmul(Data[:, 3:-1], max_cols[:-1, :-1]),sparse,T,Cs)
squared_errors = [error**2 for error in errors]
np.mean(squared_errors)

0.002698558290067975